apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app3
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-app3
  template:
    metadata:
      labels:
        app: sample-app3
    spec:
      containers:
      - command:
        - /app/sample-app3
        image: gitopsbook/sample-app3:latest
        name: sample-app3
        ports:
        - containerPort: 8080
