apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-app2
  template:
    metadata:
      labels:
        app: sample-app2
    spec:
      containers:
      - command:
        - /app/sample-app2
        image: gitopsbook/sample-app2:latest
        name: sample-app2
        ports:
        - containerPort: 8080
